print("<Abdulkader Safi />")

require("safi.plugins-setup")

require("safi.core.colorscheme")
require("safi.core.options")
require("safi.core.keymaps")

require("safi.plugins.comment")
require("safi.plugins.lualine")
require("safi.plugins.telescope")
require("safi.plugins.nvim-cmp")
require("safi.plugins.treesitter")
require("safi.plugins.autopairs")
require("safi.plugins.gitsigns")
require("safi.plugins.git")
require("safi.plugins.lsp-zero")
require("safi.plugins.mason")
require("safi.plugins.lsp-config")
require("safi.plugins.prettier")
require("safi.plugins.null-ls")
require("safi.plugins.colorizer")
-- require("safi.plugins.ts-autotag")
